# Generated by Django 6.0.1 on 2026-01-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="place",
            field=models.CharField(default="", max_length=50),
        ),
    ]
