# Generated by Django 6.0.1 on 2026-01-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_remove_customer_address_customer_password_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="place",
            new_name="type",
        ),
        migrations.AddField(
            model_name="customer",
            name="reset_otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
