# Generated by Django 6.0.1 on 2026-01-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_rename_place_customer_type_customer_reset_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
