# Generated by Django 6.0.1 on 2026-01-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_address_user_password_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=20),
        ),
    ]
