# Generated by Django 6.0.1 on 2026-01-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
